apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kubernetes-deployment
spec:
  selector:
    matchLabels:
      app: docker-kubernetes-deployment
  template:
    metadata:
      labels:
        app: docker-kubernetes-deployment
    spec:
      containers:
      - name: docker-kubernetes-deployment
        image: tarunkumar04/docker-kubernetes-app
        ports:
        - containerPort: 8100
