apiVersion: apps/v1
kind: Deployment
metadata:
  name: DockerKubernetesDeployment
spec:
  selector:
    matchLabels:
      app: DockerKubernetesDeployment
  template:
    metadata:
      labels:
        app: DockerKubernetesDeployment
    spec:
      containers:
      - name: DockerKubernetesDeployment
        image: tarunkumar04/demoservice:latest
        ports:
        - containerPort: 8100
