apiVersion: v1
kind: Service
metadata:
  name: DockerKubernetesDeployment
spec:
  type: NodePort
  selector:
    app: DockerKubernetesDeployment
  ports:
  - port: 8100
    targetPort: 8100
    nodePort: 30002