apiVersion: v1
kind: Service
metadata:
  name: docker-kubernetes-deployment
spec:
  type: NodePort
  selector:
    app: docker-kubernetes-deployment
  ports:
  - port: 8100
    targetPort: 8100
    nodePort: 30002